name: 01 - Hello

on:
  workflow_dispatch:

jobs:
  saludar:
    runs-on: ubuntu-24.04
    steps:
      - name: Saludo
        run: echo "Hola desde GitHub Actions!"
      - name: Fecha
        run: date
      - name: Listar archivos
        run: ls -la

  repo-files:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Listar archivos
        run: ls -la
