name: 05 - CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  frontend-lint:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: 12-ejercicio-cicd
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-pnpm-ci-cd
      - run: pnpm lint:frontend

  frontend-test:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: 12-ejercicio-cicd
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-pnpm-ci-cd
      - run: pnpm test:frontend

  backend-lint:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: 12-ejercicio-cicd
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-pnpm-ci-cd
      - run: pnpm lint:backend

  backend-test:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: 12-ejercicio-cicd
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-pnpm-ci-cd
      - run: pnpm test:backend

  frontend-build:
    runs-on: ubuntu-24.04
    needs: [frontend-lint, frontend-test]
    defaults:
      run:
        working-directory: 12-ejercicio-cicd
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-pnpm-ci-cd
      - run: pnpm build:frontend

  backend-build:
    runs-on: ubuntu-24.04
    needs: [backend-lint, backend-test]
    defaults:
      run:
        working-directory: 12-ejercicio-cicd
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-pnpm-ci-cd
      - run: pnpm build:backend